### ISSUE TITLE
Optimizer should optimize the ContainerVisual created just for clipping if possible.

### ISSUE THREAD

**Issue by plaiMS** [CommunityToolkit/Lottie-Windows#128]

**Comment by simeoncran** [comment]
The optimizer should try to push down the Clip on ContainerVisuals that have a single child.
Also if there's only a ShapeVisual below a ContainerVisual with a clip, the clip can be optimized away because ShapeVisual's clip to their size.

**Comment by nishitha-burman** [comment]
Currently there are no plans to support this.
