### ISSUE TITLE
Add support for grouped animated paths

### ISSUE THREAD

**Issue by simeoncran** [CommunityToolkit/Lottie-Windows#263]
Currently, if there are multiple paths in the same shape, we are unable to render if any of the paths is animated. We can probably do better. Needs some investigation. Comp will handle animating Win2D groups which have the same number of control points, so in most cases we just need to convert the paths to Win2d groups.

Then there are a couple of stages:
1. If only 1 path is animated, create grouped paths for each of the key frames in the animated path.
2. If more than 1 path is animated and each animated path has the same keyframe offsets and easings create grouped paths for each of the key frames in the animated paths.
3. If more than 1 path is animated and the animated paths have different keyframes offsets create grouped paths for each of the unique keyframes offsets, interpolating the paths to create keyframes.
If there are different easings on keyframes with the same offset, we probably can't handle it.

**Comment by nishitha-burman** [comment]
Currently there are no plans to support this.
