### ISSUE TITLE
Make gradient stop optimizer deterministic

### ISSUE THREAD

**Issue by simeoncran** [CommunityToolkit/Lottie-Windows#300]
The gradient stop optimizer can produce different results from run to run (i.e. it is not deterministic). This isn't a big deal to the generated code, but it does create noise when we compare the outputs from LottieGen after a change.

I don't know what is causing the non-determinism, but a typical cause is from enumerating the values in a dictionary where the hashcodes of the values are non-deterministic.

**Comment by nishitha-burman** [comment]
Currently there are no plans to add this.
