### ISSUE TITLE
TrimPath is sometimes wrong for Rectangle/RoundedRectangle/Ellipse geometries

### ISSUE THREAD

**Issue by simeoncran** [CommunityToolkit/Lottie-Windows#317]
Just found out that trim is not well defined for CompositionRectangleGeometry, CompositionRoundedRectangleGeometry, CompositionEllipseGeometry. The problem is that trim is relative to the starting point of the drawing, but that isn't defined by D2D (which is the implementation used by Windows.UI.Composition) except for paths.

The problem became apparent when we trimmed a CompositionRoundedRectangleGeometry. The start of the trim depends on the corner radius value, which means that the trim got unexpectedly rotated.

The required fix is to have the translator convert all non-path geometries to paths if any trim path is specified.

**Comment by simeoncran** [comment]
After more discussion, trim in Composition now is well-defined (nobody wanted to commit to the definition before, but we're all comfortable that the trim behavior can be documented now and will stay the same). However it turns out that trimming with AE RoundCorners works differently from trimming without RoundCorners.

In AE, the start of drawing for a rectangle is at the line that is clockwise AFTER the bezier defining the top right corner. But if there's a RoundCorners between the Rectangle and the Trim Path, and the rectangle's roundness value is 0 (important because Round Corners is ignored if roundness != 0), then the start of drawing is AT the bezier defining the top right corner.

Lottie-Windows needs to recognize that case and adjust the start of drawing.

Note that converting non-path geometries to paths (as I was suggesting above) will not work in general. The problem is that Composition can only animated between paths using a single easing. But AE allows different easings for different parameters of a path (e.g. a rectangle's X and Y values can be animated with different curves). For Composition to be as expressive as AE we'd need to have the ability animate path parameters, not just interpolate between paths, for example, we'd need to be able to individually animate the position of a point in a path.

**Comment by nishitha-burman** [comment]
Currently there are no plans to add this.
