### ISSUE TITLE
lottiegen warning message

### ISSUE THREAD

**Issue by HppZ** [CommunityToolkit/Lottie-Windows#482]
warning LP0017: Unexpected field: l.
warning LP0017: Unexpected field: ReadAnimatableVector3.l.

**Comment by HppZ** [comment]
and my lottie json file does not look correct in lottie-viewer app.

**Comment by HppZ** [comment]
I can provide you my json file by email attachment if you need.

**Comment by HppZ** [comment]
@HavenDV PLEASE HELP

**Comment by aborziak-ms** [comment]
Hm, Warning LP0017 should not cause any issue.
@HppZ yes we will need your json file to find the exact problem

**Comment by HppZ** [comment]
> Hm, Warning LP0017 should not cause any issue. @HppZ yes we will need your json file to find the exact problem

your email please.

**Comment by aborziak-ms** [comment]
@HppZ temporary.email.7451359@gmail.com

**Comment by HppZ** [comment]
> @HppZ [temporary.email.7451359@gmail.com](mailto:temporary.email.7451359@gmail.com)

sent.

**Comment by aborziak-ms** [comment]
> > @HppZ [temporary.email.7451359@gmail.com](mailto:temporary.email.7451359@gmail.com)
> 
> sent.

Ok I see the difference, I will investigate this problem.
