### ISSUE TITLE
Can not play a lottie json file

### ISSUE THREAD

**Issue by xiejiang2014** [CommunityToolkit/Lottie-Windows#487]
lottie viewer can not play this json file.
https://lottiefiles.com/88348-blob

**Comment by aborziak-ms** [comment]
Are you using the latest version of Lottie-Viewer? Or do you see any issues in issues tab?

It seems playing just fine for me:
![image](https://user-images.githubusercontent.com/83784664/153277281-cd383270-c9e1-429a-a47f-228a1494bd17.png)

**Comment by xiejiang2014** [comment]
thank you for your reply
I tested:
1 Lottie Viewer 7.0.0.0 (Microsoft Store)
2 The latest version compiled from the main branch

Open https://lottiefiles.com/88348-blob to see that lottie json is dynamic in web browser,
But only the first frame is displayed in Lottie Viewer, and clicking the play button cannot make it animated.

thanks.

**Comment by aborziak-ms** [comment]
@xiejiang2014 I see that 7.0.6 is available in the store. This animation is not working for version 7.0.0, we added support for rounded corners animation after 7.0.0

**Comment by xiejiang2014** [comment]
Yes,I see the issue now,   

LT0034 Path animation requires a UAP version of as least 11.

but where can i get UAP 11? Is windows 11 required?

thanks.

**Comment by xiejiang2014** [comment]
In vs 2022, I didn't find the 19645 version, but I installed 20348 and 22000, and my window 10 version is 21H1 (19043.1526), which is still not playable.
I will try to upgrade to 21H2.
thanks.

**Comment by xiejiang2014** [comment]
![Snipaste_2022-02-18_22-58-02](https://user-images.githubusercontent.com/44390984/154707114-7aa86e48-0b7f-4811-a633-9f7a47a231e1.png)

![Snipaste_2022-02-18_22-58-21](https://user-images.githubusercontent.com/44390984/154707245-566476b0-7426-4102-854e-bfe3b2f96477.png)

Windows 10 21H2 (19044.1526)

Image is still static.

Maybe need a Windows 10 Insider Preview version?
