### ISSUE TITLE
Lottie animation plays in Mobile and Web but not for Desktop (UWP)

### ISSUE THREAD

**Issue by MarkIvanDev** [CommunityToolkit/Lottie-Windows#493]
This lottie animation plays in Mobile (using LottieFiles in Android) and Web (using LottieFiles.com) but it does not play using the Lottie Viewer in the Microsoft Store.
[Lottie Animation.zip](https://github.com/CommunityToolkit/Lottie-Windows/files/8182417/Lottie.Animation.zip)

It shows this when viewing in Lottie Viewer:
![UWP Lottie Viewer](https://user-images.githubusercontent.com/16188252/156683586-d7284215-abba-41b8-95e4-c32b129447b1.png)

It shows this in LottieFiles.com:
![LottieFiles.com](https://user-images.githubusercontent.com/16188252/156683712-2adbd002-5c60-4a88-934f-fa2b2d1c06c1.png)

It shows this in LottieFiles in Android:
![LottieFiles in Android](https://user-images.githubusercontent.com/16188252/156684037-10590265-30b2-4ede-a19e-828e2621b941.jpg)

It doesn't show also when using the `LottieVisualSource` in UWP projects. And it also does not  show the fallback content when using this lottie file.

I am using the following versions:
Microsoft.Toolkit.Uwp.UI.Lottie v7.1.0
Lottie Viewer v7.1.0

**Comment by aborziak-ms** [comment]
@MarkIvanDev the problem with this specific animation is that it uses a keyframe path animation with a different number of segments between keyframes. Unfortunately current Windows Composition API does not support this, so LottieViewer fails to present the animation on the screen. I will try to find a workaround for this

**Comment by MarkIvanDev** [comment]
Thank you. Is this fix in the current version of NuGet package (v7.1.1)?
