### ISSUE TITLE
Q: What is the codegen process for LottieViewer_04_Playback and UiFeedbackAnimations

### ISSUE THREAD

**Issue by ptran-gpfw** [CommunityToolkit/Lottie-Windows#496]
Under

    LottieViewer\AnimatedVisuals\

I see these files:
* LottieViewer_04_Playback.cs
* UiFeedbackAnimations.cs

I would like to learn more about the codegen process.

Where is the json source, `LottieViewer_04_Playback.json` located?
Also, how is `UiFeedbackAnimations.cs` generated?

**Comment by aborziak-ms** [comment]
You can find sample lottie animations (.json files) in `samples/LottieSamples/Assets` folder. Thy are exported from After Effects using bodymovin plugin.

To generate the code (.cs or .cpp) that runs the animation you can use command line tool `LottieGen` (https://github.com/CommunityToolkit/Lottie-Windows/tree/main/LottieGen, https://docs.microsoft.com/en-gb/windows/communitytoolkit/animations/lottie-scenarios/getting_started_codegen). It will generate you .cs or .cpp files, depending on the language that you need.

**Comment by ptran-gpfw** [comment]
Thanks @aborziak-ms, I understand the general codegen process, and I'm aware of the samples.

However, I am specifically asking about **LottieViewer**. I'm guessing the bodymovin json files were simply not committed to the repo, but I didn't want to make assumptions.

**Comment by aborziak-ms** [comment]
@ptran-gpfw oh I see, yes these specific animations (json) were not committed to the repo, only generated code.
