### ISSUE TITLE
Can this library be used by win32 program?

### ISSUE THREAD

**Issue by BrookZhu** [CommunityToolkit/Lottie-Windows#498]
I have a win32 program and want to use a lottie library to display lottie animation. If the library can be used by win32 program？

**Comment by BrookZhu** [comment]
@aborziak-ms  can you help to reply?

**Comment by aborziak-ms** [comment]
@BrookZhu I don't think that you can use Lottie-Windows directly, but you can try generating code using LottieGen and then using this code and an instance of compositor to display some visual in the app
