### ISSUE TITLE
Wrong generated .CS

### ISSUE THREAD

**Issue by steam3d** [CommunityToolkit/Lottie-Windows#512]
I has the WelcomeScreen_2.json animation. It works fine when i play it as .json. 
I tried to generate the cs code using command
`LottieGen -Language CSharp -Public -WinUIVersion 2.4 -InputFile WelcomeScreen_2.json`

It generated the WelcomeScreen_2.cs file with errors.
![image](https://user-images.githubusercontent.com/30986874/174451437-ced0059b-a351-4b4d-8e46-267e1618c6f9.png)

I tried to fix errors, but got the other error:
![image](https://user-images.githubusercontent.com/30986874/174451503-cdba50b9-f343-4cf5-bb81-1b7f593635e6.png)

[WelcomeScreen_2.zip](https://github.com/CommunityToolkit/Lottie-Windows/files/8934102/WelcomeScreen_2.zip)

**Comment by aborziak-ms** [comment]
Fixed in #549 , will be included in next release.
