### ISSUE TITLE
Incorrect drawing animation

### ISSUE THREAD

**Issue by workhardrene** [CommunityToolkit/Lottie-Windows#521]
Hi! I am swift developer and working on IOS Project
I have a circle turn on button and when i tried checking .json on lottieFiles.com animation is looking good but when i running on IOS device all border are square 

`
        func play(animation: String) {
        let animation = Animation.named(animation, subdirectory: "lottie")
        self.animationViewLayer.animation = animation
        self.animationViewLayer.layer.masksToBounds = false
        self.animationViewLayer.contentMode = .scaleAspectFill
        self.animationView.addSubview(self.animationViewLayer)
        
        self.animationViewLayer.shouldRasterizeWhenIdle = true
        self.animationViewLayer.autoPinEdgesToSuperviewEdges()
        self.animationView.backgroundColor = .clear
        self.animationViewLayer.play()
        if VPNManager.shared().status == .disconnected {
            self.animationViewLayer.loopMode = .loop
        }
        else {
            self.animationViewLayer.loopMode = .playOnce
        }
        self.animationViewLayer.backgroundBehavior = .pauseAndRestore
    }

`
I attaching screenshot how it look on device
![2022-08-24 09 56 29](https://user-images.githubusercontent.com/111957142/186351414-d1963c16-72df-4369-8def-3553beb2c7c0.jpg)

please any help will be useful

**Comment by aborziak-ms** [comment]
Seems not related to Lottie-Windows.
