### ISSUE TITLE
How to update the project files?

### ISSUE THREAD

**Issue by r2d2Proton** [CommunityToolkit/Lottie-Windows#537]
I am getting the following error:

DEP0800: The required framework "C:\Users\Jerry\.nuget\packages\runtime.win10-x64.microsoft.net.uwpcoreruntimesdk\2.2.12\build\..\tools\Appx\Microsoft.NET.CoreRuntime.2.2.appx" failed to install. [0x80073CF0] Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570.			LottieSamples		

And I have tried for hours to get the project upgraded to simply build. AND HOURS. To simply build. I am using VS 2022 17.8.0.

**Comment by aborziak-ms** [comment]
@r2d2Proton it doesn't look like an error related to Lottie-Windows project itself, it seems that there is something wrong with your Visual Studio installation. You should try to modify your VS installation by tweaking the components on "Individual components" page in Visual Studio Installer.
