### ISSUE TITLE
Lottie-Windows Component List

### ISSUE THREAD

**Issue by r2d2Proton** [CommunityToolkit/Lottie-Windows#552]
_Follow-up from: https://github.com/CommunityToolkit/Lottie-Windows/issues/537_

"it doesn't look like an error related to Lottie-Windows project itself, it seems that there is something wrong with your Visual Studio installation. You should try to modify your VS installation by tweaking the components on "Individual components" page in Visual Studio Installer."

Thank you for the response. What are the needed components for Visual Studio 2022 17.9.2?

The workload needed to get this to build and deploy on my Windows 11 desktop?

**Comment by r2d2Proton** [comment]
No one has a list of the needed components to get this to deploy on my Windows 11 desktop?

**Comment by aborziak-ms** [comment]
You need to install Visual Studio 2022 and default .NET Desktop Development components, that is it.

**Comment by r2d2Proton** [comment]
The build and launch failed. After installing both dotnet-sdk-5.0.408-win-x64.exe and dotnet-runtime-5.0.17-win-x64.exe, rebooting, and trying to get the project to launch I get the below error. Do I need to tell VS2022 where the .Net was installed?

![VisualStudioComponents01](https://github.com/CommunityToolkit/Lottie-Windows/assets/4054178/08e10b53-7182-4187-bbe3-9eb788356123)

**Comment by r2d2Proton** [comment]
Getting this working is becoming a high priority for me. @aborziak-ms I followed the steps and still encounter the deployment problem. Any other suggestions you have? By chance, can you share your Individual Modules list, and all the components you have?

**Comment by aborziak-ms** [comment]
Have you tried installing the framework from the error?
What exactly you are trying to build? It looks like the error is from building LottieSamples, have you tried building LottieGen or Lottie-Windows-WinUI?

And what are you trying to achieve? If you need Lottie-Windows for your project you do not need to build it, you can use nuget packages for WinUI3 or UWP, or use LottieGen tool.

**Comment by r2d2Proton** [comment]
@aborziak-ms thank you for the response. I am trying to use the Lottie tools, a lot of nice work put into it, as a baseline for an in-house editor tool. Some of the Lottie animations need changes, and certainly can manually change the JSON files but not the best approach. That is an approach of last resort. I am trying to get a debug build and deploy on my Windows 10 machine so I can start working with it. And I have tried UWP and WinUI3. But neither have succeeded. Will use whatever works reliably. Take it with a grain of salt. Historically used a lot of assembly, C, C++, got into C# with Creators Club. Still like the projects and assets today :) Definitely a lot of holes with .NET Framework, C#, and Visual Studio settings. . but will try my best to get things working and understand the relationships between different pieces.

**Comment by aborziak-ms** [comment]
This project will not let you view or edit json lotties. To edit lottie animations I think the only way is to tweak original aftereffects file and re-export it, I haven't heard about any direct lottie json editors.

You need to build this project locally only if you want to contribute by fixing some bug, or if you want to do some code changes specific to your use that are not in current release of LottieGen or Lottie-Windows WinUI3 or UWP nuget packages. So it does not seem to me that you need to build it locally. If you want to just use lottie animations in your app, you should follow quick start in the readme.

**Comment by r2d2Proton** [comment]
The Lottie animations are working. And I want to build this locally for my needs.

**Comment by michael-hawker** [comment]
@aborziak-ms they're trying to build the [Lottie Viewer app](https://www.microsoft.com/store/productId/9P7X9K692TMW) locally. Has that been updated in the store any time recently? Source here: https://github.com/CommunityToolkit/Lottie-Windows/tree/main/LottieViewer

@r2d2Proton it's a UWP app, so it should require this workload as well:

![image](https://github.com/CommunityToolkit/Lottie-Windows/assets/24302614/ccabf9b0-ef48-4caa-ab7d-5c38a572789a)

Along with the corresponding Windows SDK version. It will probably install the latest by default, though generally it'll prompt to update the project if there's a mismatch.

Otherwise, your machine may be in a weird state? I did stumble upon [this blog](https://www.michaelrinderle.com/2020/05/29/fixing-a-uwp-net-core-missing-framework-issue/), but I'd try the above workload and SDK stuff first.

**Comment by r2d2Proton** [comment]
Thank you @michael-hawker Attached is what I have now:
![Components](https://github.com/CommunityToolkit/Lottie-Windows/assets/4054178/dba7ebcf-233f-4854-b32f-f27d4ff0fec2)

**Comment by r2d2Proton** [comment]
@michael-hawker I will uninstall the .NET Core SDK 2.2 versions.

![NETCore2 2Frameworks](https://github.com/CommunityToolkit/Lottie-Windows/assets/4054178/e88c13a1-faa8-4161-a5f4-5daa3fcfe5c1)

**Comment by r2d2Proton** [comment]
@michael-hawker made sure the folder was empty:
```text
C:\Users\Jerry.nuget\packages\runtime.win10-x64.microsoft.net.uwpcoreruntimesdk
```
Cloned the repo and opened up the VS solution. After doing so noticed the 2.2.12 folder was created. If I try to install the C:\Users\Jerry\.nuget\packages\runtime.win10-x64.microsoft.net.uwpcoreruntimesdk\2.2.12\tools\Appx\Microsoft.NET.CoreRuntime.2.2.appx by double clicking on it and then choosing "Install" I get the following error :
```text
App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)
```

**Comment by r2d2Proton** [comment]
@michael-hawker And I tried using add-appxpackage:
```text
PS C:\Users\Jerry\.nuget\packages\runtime.win10-x64.microsoft.net.uwpcoreruntimesdk\2.2.12\tools\Appx> add-appxpackage Microsoft.NET.CoreRuntime.2.2.appx
add-appxpackage : Deployment failed with HRESULT: 0x80073CF0, Package could not be opened.
Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570.
NOTE: For additional information, look for [ActivityId] a1762145-759f-000c-a293-d4a19f75da01 in the Event Log or use the command line Get-AppPackageLog -ActivityID a1762145-759f-000c-a293-d4a19f75da01
At line:1 char:1
+ add-appxpackage Microsoft.NET.CoreRuntime.2.2.appx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (C:\Users\Jerry\...untime.2.2.appx:String) [Add-AppxPackage], FileNotFoundException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

The Get-AppPackageLog note looks very helpful. The contents are:
```text
PS C:\Users\Jerry\.nuget\packages\runtime.win10-x64.microsoft.net.uwpcoreruntimesdk\2.2.12\tools\Appx> Get-AppPackageLog -ActivityID a1762145-759f-000c-a293-d4a19f75da01

Time                      ID           Message
----                      --           -------
3/14/2024 1:01:58 PM      603          Started deployment Add operation on a package with main parameter Microsoft.NET.CoreRuntime.2.2.appx and Options 0 and 0. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
3/14/2024 1:01:58 PM      495          Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570.
3/14/2024 1:01:58 PM      402          error 0x80070570: Reading manifest from location: Microsoft.NET.CoreRuntime.2.2.appx failed with error: The file or directory is corrupted and unreadable.
                                       .
3/14/2024 1:01:58 PM      486          AppX Deployment operation failed with error 0x80070490 from API Could not find package name in path
3/14/2024 1:01:58 PM      404          AppX Deployment operation failed for package  with error 0x80073CF0. The specific error text for this failure is:
                                       Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570.
```

**Comment by r2d2Proton** [comment]
@michael-hawker My newly setup laptop, with VS just installed, I do not see the problem. LottieViewer with "Any CPU" will not launch by pressing F5. I noticed in the Configuration Manager LottieViewer had an x86 configuration defined. So I changed the build configuration to match and LottieViewer worked as expected. I thought "Any CPU" would work but did not.

<img width="817" alt="LottieViewerx86" src="https://github.com/CommunityToolkit/Lottie-Windows/assets/4054178/523726b3-8c6d-4179-a2fe-b43f12d4dce4">

**Comment by r2d2Proton** [comment]
Thank you for your help @michael-hawker @aborziak-ms . After formatting my internal hard-drive and reinstalling Windows 11, and Visual Studio, the build, deploy, and debug work as expected. But one notable difference is that I had upgraded to Pro as in Windows 11 Pro from Home. The newly installed version was the Home edition.
